services:
  db:
    image: postgres:13.16
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: Pg1234
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - fake_net      
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: fabriciosveronez/live-fake-shop:v1
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: ecommerce
      DB_PASSWORD: Pg1234
      DB_NAME: ecommerce
      DB_PORT: 5432
      FLASK_APP: index.py
      PROMETHEUS_MULTIPROC_DIR: /tmp/metrics
    networks:
      - fake_net
    depends_on:
      - db
      
networks:
  fake_net:
    driver: bridge

volumes:
  postgres_data:
