kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 5000
- role: control-plane
- role: control-plane
- role: worker
- role: worker
- role: worker
